name: Deploy Hugo site to gh-pages branch

on:
  # 推送到主分支时触发
  push:
    branches: ["main", "master"]
  # 允许手动触发
  workflow_dispatch:

# 设置权限
permissions:
  contents: write

# 默认使用 bash
defaults:
  run:
    shell: bash

jobs:
  # 构建和部署任务
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 获取 Hugo 主题
          fetch-depth: 0    # 获取完整历史

      - name: 设置 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: 构建网站
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://xiaouba.github.io/"

      - name: 部署到 gh-pages 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true